import { Product } from "./types"

export const products : Product[] = [
{
    id: 1,
    title : "Women Black Jeans",
    image : ["/assets/blackjeans.jpg",],
    slug: "black-jeans",
    price: 120,
    discount: 0,
    category: "pants",
    description: "Best quality jeans for women in black with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},
{
    id: 2,
    title : "Women Blue Jeans",
    image : ["/assets/bluejeans.jpg",],
    slug: "blue-jeans",
    price: 120,
    discount: 0,
    category: "pants",
    description: "Best quality jeans for women in blue with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},
{
    id: 3,
    title : "Women White Pant",
    image : ["/assets/whitepant.jpg",],
    slug: "white-pant",
    price: 120,
    discount: 60,
    category: "pants",
    description: "Best quality pant for women in white with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},
{
    id: 4,
    title : "Women Blue Pant",
    image : ["/assets/bluepant.jpg",],
    slug: "blue-pant",
    price: 120,
    discount: 20,
    category: "pants",
    description: "Best quality pant for women in blue with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},
{
    id: 5,
    title : "Women Black Jeans",
    image : ["/assets/blackjeans.jpg",],
    slug: "black-Jeans",
    price: 120,
    discount: 20,
    category: "pants",
    description: "Best quality jeans for women in black with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},
{
    id: 6,
    title : "Women Blue Jeans",
    image : ["/assets/bluejeans.jpg",],
    slug: "blue-Jeans",
    price: 120,
    discount: 0,
    category: "pants",
    description: "Best quality jeans for women in blue with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},
{
    id: 7,
    title : "Women White Pamt",
    image : ["/assets/whitepant.jpg",],
    slug: "white-Pant",
    price: 120,
    discount: 35,
    category: "pants",
    description: "Best quality pant for women in white with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},
{
    id: 8,
    title : "Women Blue Pant",
    image : ["/assets/bluepant.jpg",],
    slug: "blue-Pant",
    price: 120,
    discount: 0,
    category: "pants",
    description: "Best quality pant for women in blue with soft stuff.",
    size: ["S","M","L","XL"],
    color: ["#ffffff","#000000","#e60000"],
    qty:1,
},

]
